version: '3'
services:
  web:
    volumes:
      - ./:/app

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "${DYNAMO_PORT}:${DYNAMO_PORT}"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${REGION}
      - DYNAMO_PORT=${DYNAMO_PORT}
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./infrastructure/dynamodb-local-db/:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-local-init-table:
    image: amazon/aws-cli
    container_name: dynamodb-local-init-table
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${REGION}
      - DYNAMO_TABLE_NAME=${DYNAMO_TABLE_NAME}
      - DYNAMO_ENDPOINT=${DYNAMO_ENDPOINT}
    command: >-
      dynamodb create-table
          --table-name ${DYNAMO_TABLE_NAME}
          --attribute-definitions AttributeName=id,AttributeType=S
          --key-schema AttributeName=id,KeyType=HASH
          --billing-mode PAY_PER_REQUEST
          --endpoint-url ${DYNAMO_ENDPOINT} --region ${REGION}
    restart: on-failure:2 # prevent flaky bug where table seed fails occasionally on first attempt

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    ports:
      - "${DYNAMO_ADMIN_PORT}:${DYNAMO_ADMIN_PORT}"
    environment:
      - DYNAMO_ENDPOINT=${DYNAMO_ENDPOINT}
      - DYNAMO_ADMIN_PORT=${DYNAMO_ADMIN_PORT}